import type { Metadata } from "next";
import { Inter } from "next/font/google";
// 5:57:29
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Whole App Layout

// export default function RootLayout({
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // 5:57:40
  const session = await auth();
  // console.log("Layout:", session); // Yes, I can get session in Terminal

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
